### PR TITLE
enable code and resource shrinking for smaller app size

### PR DESCRIPTION
**Pull request by connyduck**
release apk size before: 6.880kB
release apk size after: 2.430kB

### CODE REVIEW

**Comment by p1gp1g** [comment]
This doesn't work with Nextcloud-SingleSignOn: I've already broken NextPush because of this :smiling_face_with_tear: : https://github.com/nextcloud/Android-SingleSignOn/issues/488 and we should test their solution to minify the app : https://github.com/nextcloud/Android-SingleSignOn/pull/545/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R276

**Comment by connyduck** [comment]
Yes they bundled R8 rules into the library and now everything works fine. I tried it out. In case I missed something please point me to the specific thing that is broken and I will fix it.

**Comment by p1gp1g** [comment]
I thought we had to add `-dontobfuscate` and `-keep class my.class.*` to the proguard rules before

**Comment by connyduck** [comment]
Regarding `-dontobfuscate`, I don't think it is necessary and also a bad idea, see here: https://github.com/nextcloud/Android-SingleSignOn/issues/572
Regarding the other thing, I'll double check that.

**Comment by connyduck** [comment]
I should have checked better the first time, but now the necessary rules are added.

**Comment by p1gp1g** [comment]
Thanks again :)

**Pull request merged**
